# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_updated_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='UserModel',
        ),
    ]
